### PR TITLE
v1.1.0

### PR DESCRIPTION
**Pull request by jethror1**
## Changes

- Apps updated:
  - eggd_athena v1.4.0 -> v1.5.0
  - eggd_tso500_rescue v1.0.0 -> eggd_vcf_rescue v1.1.0
  - eggd_generate_variant_workbook v2.1.1 -> v2.3.0

- Other changes
  - added `panel_filters` supported by athena v1.5.0 as requested by solid cancer team
  - updated transcript list for eggd_vep
  - workbook config changes:
    - add colouring of  VF column cells
    - add basic summary
    - increased filtering to exclude gnomAD exomes / genomes >1% and  VF <5%
    - slight column reordering

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_TSO500_reports_workflow/2)

### CODE REVIEW

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_TSO500_reports_workflow/2)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[`dxworkflow.json` line 59 at r1](https://reviewable.io/reviews/eastgenomics/eggd_TSO500_reports_workflow/2#-NMU0uCI6GAvWBieh4P1:-NMU0uCJ55mCIOONcaCf:b21xfic) ([raw file](https://github.com/eastgenomics/eggd_TSO500_reports_workflow/blob/39363256d25e5a8f4e9f31a4a33f89838e2b337a/dxworkflow.json#L59)):*
> ```JSON
>       "id": "stage-GF25f384b0bVZkJ2P46f79xy",
>       "executable": "app-eggd_vcf_rescue/1.1.0",
>       "folder": "TSO500_rescue_1.1.0",
> ```

update folder name to match the app name
___
*[`README.md` line 16 at r1](https://reviewable.io/reviews/eastgenomics/eggd_TSO500_reports_workflow/2#-NMU1g8l0qOAh1uSToBN:-NMU1g8l0qOAh1uSToBO:b-1miozo) ([raw file](https://github.com/eastgenomics/eggd_TSO500_reports_workflow/blob/39363256d25e5a8f4e9f31a4a33f89838e2b337a/README.md#L16)):*
> ```Markdown
> |mosdepth           |1.0.1|
> |athena             |1.5.0|
> |eggd_tso500_rescue |1.1.0|
> ```

update app name

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_TSO500_reports_workflow/2)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @Aisha-D)

___
*[`dxworkflow.json` line 59 at r1](https://reviewable.io/reviews/eastgenomics/eggd_TSO500_reports_workflow/2#-NMU0uCI6GAvWBieh4P1:-NMUA5yS2oZ8kyFQ8Mbc:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_TSO500_reports_workflow/blob/39363256d25e5a8f4e9f31a4a33f89838e2b337a/dxworkflow.json#L59)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

update folder name to match the app name
</blockquote></details>

Done.
___
*[`README.md` line 16 at r1](https://reviewable.io/reviews/eastgenomics/eggd_TSO500_reports_workflow/2#-NMU1g8l0qOAh1uSToBN:-NMUA54B3MAFmvs0gaND:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_TSO500_reports_workflow/blob/39363256d25e5a8f4e9f31a4a33f89838e2b337a/README.md#L16)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

update app name
</blockquote></details>

Done.

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_TSO500_reports_workflow/2)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[`dxworkflow.json` line 59 at r1](https://reviewable.io/reviews/eastgenomics/eggd_TSO500_reports_workflow/2#-NMU0uCI6GAvWBieh4P1:-NMUAXkHDv6-KR_lCbMk:b1beoy6) ([raw file](https://github.com/eastgenomics/eggd_TSO500_reports_workflow/blob/39363256d25e5a8f4e9f31a4a33f89838e2b337a/dxworkflow.json#L59)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

it doesn't need the eggd_ as it is an app

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_TSO500_reports_workflow/2)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Aisha-D)

___
*[`dxworkflow.json` line 59 at r1](https://reviewable.io/reviews/eastgenomics/eggd_TSO500_reports_workflow/2#-NMU0uCI6GAvWBieh4P1:-NMUBZI43co3bPY17G8d:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_TSO500_reports_workflow/blob/39363256d25e5a8f4e9f31a4a33f89838e2b337a/dxworkflow.json#L59)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

it doesn't need the eggd_ as it is an app 
</blockquote></details>

Done.

**Review by Aisha-D — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_TSO500_reports_workflow/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jethror1)

**Pull request merged**
