### PR TITLE
New process for updating helios

### PR DESCRIPTION
**Pull request by fletchercr**
Changes: 

- Updated README with tso500 launcher description
- Added the tso500_reports_workflow launcher script v1.2.2 to the workflow repo

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_TSO500_reports_workflow/28)

### CODE REVIEW

**Review by Aisha-D — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_TSO500_reports_workflow/28)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @fletchercr)

___
*[`helios_reports_workflow_launcher_v1.2.2.sh` line 7 at r1](https://reviewable.io/reviews/eastgenomics/eggd_TSO500_reports_workflow/28#-NvlW1NgCG5s9S8incWG:-NvlW1NgCG5s9S8incWH:bnd7h9d) ([raw file](https://github.com/eastgenomics/eggd_TSO500_reports_workflow/blob/d2cfd8d37bf94f2a7ddd82b001d3c79aef8a715c/helios_reports_workflow_launcher_v1.2.2.sh#L7)):*
> ```Shell
> 
> # define the REPORTS WORKFLOW VERSION to use (currently v1.4.2)
> workflow_id="workflow-GjKQqBj4yfK1yYzXXbypQyZ7"
> ```

in the current launcher script, it points with the project ID included. Might want to keep the same structure (not sure if it was done intentionally to include project ID to avoid archiving issues)
___
*[`README.md` line 40 at r1](https://reviewable.io/reviews/eastgenomics/eggd_TSO500_reports_workflow/28#-NvlVObM6TLt0_oiKeac:-NvlVObM6TLt0_oiKead:bilq20q) ([raw file](https://github.com/eastgenomics/eggd_TSO500_reports_workflow/blob/d2cfd8d37bf94f2a7ddd82b001d3c79aef8a715c/README.md#L40)):*
> ```Markdown
> ```
> # USAGE
> # bash helios_reports_workflow_launcher_v1.2.1.sh <output_path>
> ```

remove the version here, laeve it as hash

**Comment by fletchercr** [comment]
I explained not having the project ID in a previous PR I did to update the tso500_reports_workflow_launcher to v1.2.2 using the previous updating process: https://github.com/eastgenomics/TSO500_reports_workflow_launcher/pull/6. The workflow is still not signed off, so it's not in 001_Ref. I can either add the 001_Ref project ID here and assume it will eventually be signed off and deployed (which is technically fine for now because these changes will only go into main once everything is signed off and ready, but is it best practice?) or I can create a new PR into the "release" branch after the testing page is signed off and it would need to be merged again. 

I will make the changes to the README, thanks!

**Review by Aisha-D — COMMENTED** [review]
I see, it does make it difficuly to provide the project ID as its not live and you're bundling everything together. I think it shouldn't break anything as the [process guide](https://cuhbioinformatics.atlassian.net/wiki/spaces/O/pages/2999877633/DRAFT+Update+TSO500+reports+workflow+for+annotation+updates+v1.0.0#%F0%9F%96%A5%EF%B8%8F-Deploy-to-prod) does state to copy the workflow into 001_ref. 

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_TSO500_reports_workflow/28#-:-NvlbBI20hirLbmTEEfO:b-ktschh)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @fletchercr)

**Review by Aisha-D — COMMENTED** [review]
agreed to remove the 001_ref project IF on the basis that a copy is added to 001_ref so should point to the same object

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_TSO500_reports_workflow/28#-:-NvlxuD532QD-BJFY0pv:bg0ur05)* status: 0 of 2 files reviewed, all discussions resolved

**Review by Aisha-D — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_TSO500_reports_workflow/28)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @fletchercr)

**Pull request merged**
